apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: app
data:
  configmap_file: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit
  MONGO_HOST: mongo
  MONGO_PORT: 27017
  BG_COLOR: green
  FAIL_FLAG: 'false'
